import type { StoryNode } from "../types";

/**
 * Display helpers for a turn's authorship (human vs model vs unknown), shared
 * by the quiet status-strip indicator and the Detail-mode prose tint. The strip
 * shows only a SHORT token (the dot glyph carries origin by color); the full
 * actor · via · origin/model line is reserved for title/aria — same grammar as
 * the dee-n19h sync indicator. Theme-var colors only, so it survives all themes.
 */

/** Short token for the status strip. The ::before dot carries the rest. */
export function originToken(node: StoryNode): string {
  switch (node.origin) {
    case "model":
      return "model";
    case "human":
      return node.actor ?? "human";
    default:
      return "unknown";
  }
}

/** Always-legible detail spelling out actor · via · origin for title/aria. */
export function originDetail(node: StoryNode): string {
  const parts = [
    `origin: ${node.origin}`,
    `author: ${node.actor ?? "unknown"}`,
    `via: ${node.via ?? "unknown"}`,
  ];
  if (node.origin === "model" && node.generatedBy) {
    const g = node.generatedBy;
    const gen = [
      g.model && `model ${g.model}`,
      g.temperature !== undefined && `temp ${g.temperature}`,
      g.lengthMode && `length ${g.lengthMode}`,
    ]
      .filter(Boolean)
      .join(", ");
    if (gen) parts.push(`generated by ${gen}`);
  }
  return parts.join(" · ");
}
