import type React from "react";
import type { StoryNode } from "../types";

interface StoryTextProps {
  storyTextRef: React.RefObject<HTMLDivElement>;
  currentPath: StoryNode[];
  currentDepth: number;
  isGeneratingAt: (nodeId: string) => boolean;
}

/** Short, quiet label for the origin marker; the dot color carries the rest. */
function originLabel(node: StoryNode): string {
  switch (node.origin) {
    case "model":
      return node.generatedBy?.model
        ? `model · ${node.generatedBy.model}`
        : "model";
    case "human":
      return node.actor ?? "human";
    default:
      return "unknown";
  }
}

/** Always-legible detail spelling out actor · via · origin for title/aria. */
function originDetail(node: StoryNode): string {
  const parts = [
    `origin: ${node.origin}`,
    `author: ${node.actor ?? "unknown"}`,
    `via: ${node.via ?? "unknown"}`,
  ];
  if (node.origin === "model" && node.generatedBy) {
    const g = node.generatedBy;
    const gen = [
      g.model && `model ${g.model}`,
      g.temperature !== undefined && `temp ${g.temperature}`,
      g.lengthMode && `length ${g.lengthMode}`,
    ]
      .filter(Boolean)
      .join(", ");
    if (gen) parts.push(`generated by ${gen}`);
  }
  return parts.join(" · ");
}

export function StoryText({
  storyTextRef,
  currentPath,
  currentDepth,
  isGeneratingAt,
}: StoryTextProps) {
  // The frontier turn (deepest in view) is the one the byline describes. This
  // is the single, default-visible, quiet human-vs-model distinction, copying
  // the dee-n19h sync-indicator grammar (small, theme-var color, verbose title).
  const focus = currentPath[currentPath.length - 1];
  return (
    <div ref={storyTextRef} className="story-text">
      {currentPath.map((segment, index) => {
        const isCurrentDepth = index === currentDepth;
        const isNextDepth = index === currentDepth + 1;
        const isLoading = isGeneratingAt(segment.id);

        const spanClasses = ["story-node"];
        if (isNextDepth) {
          spanClasses.push("cursor-node");
        } else if (isCurrentDepth) {
          spanClasses.push("text-theme-text");
        } else if (index < currentDepth) {
          spanClasses.push("text-theme-text", "opacity-80");
        } else {
          spanClasses.push("text-theme-text", "opacity-55");
        }
        if (isLoading) {
          spanClasses.push("opacity-50");
        }

        if (isNextDepth) {
          const match = segment.text.match(/^([\s\S]*?)(\s*)$/);
          const body = match?.[1] ?? segment.text;
          const tail = match?.[2] ?? "";
          return (
            <span key={segment.id} data-node-id={segment.id}>
              <span
                className={spanClasses.join(" ")}
                data-origin={segment.origin}
              >
                {body}
              </span>
              {tail}
            </span>
          );
        }
        return (
          <span
            key={segment.id}
            data-node-id={segment.id}
            data-origin={segment.origin}
            className={spanClasses.join(" ")}
          >
            {segment.text}
          </span>
        );
      })}
      {focus ? (
        <span
          className={`story-origin story-origin--${focus.origin}`}
          data-origin={focus.origin}
          title={originDetail(focus)}
          aria-label={originDetail(focus)}
        >
          {originLabel(focus)}
        </span>
      ) : null}
    </div>
  );
}
