import { describe, expect, it } from "bun:test";
import { renderToStaticMarkup } from "react-dom/server";
import { AuthorshipIndicator } from "../AuthorshipIndicator";
import type { StoryNode } from "../../types";
import type { AuthorshipDisplay } from "../../lync/storyRuntime";

function render(node: StoryNode | undefined, mode: AuthorshipDisplay): string {
  return renderToStaticMarkup(<AuthorshipIndicator node={node} mode={mode} />);
}

const human: StoryNode = {
  id: "h",
  text: "A human seed.",
  continuations: [],
  origin: "human",
  actor: "ada",
  via: "textile-browser",
};
const model: StoryNode = {
  id: "m",
  text: "a model continuation.",
  continuations: [],
  origin: "model",
  actor: "ada",
  via: "textile-browser",
  generatedBy: { model: "test-model", temperature: 0.7 },
};
const unknown: StoryNode = {
  id: "u",
  text: "An imported turn.",
  continuations: [],
  origin: "unknown",
};

describe("AuthorshipIndicator", () => {
  it("renders a quiet model chip: short token + modifier class + verbose title", () => {
    const html = render(model, "ambient");
    expect(html).toContain("story-authorship-status--model");
    // Short token in the strip; the dot glyph is CSS ::before.
    expect(html).toContain(">model<");
    // The full actor · via · origin/model line lives in title + aria-label only.
    expect(html).toContain('title="origin: model');
    expect(html).toContain('aria-label="origin: model');
    expect(html).toContain("author: ada");
    expect(html).toContain("via: textile-browser");
    expect(html).toContain("generated by model test-model");
  });

  it("renders a human chip distinct from a model one", () => {
    const html = render(human, "ambient");
    expect(html).toContain("story-authorship-status--human");
    expect(html).not.toContain("story-authorship-status--model");
    expect(html).toContain(">ada<");
  });

  it("marks an unknown-origin turn as unknown, never human", () => {
    const html = render(unknown, "ambient");
    expect(html).toContain("story-authorship-status--unknown");
    expect(html).toContain(">unknown<");
    expect(html).toContain("origin: unknown");
    expect(html).not.toContain("story-authorship-status--human");
  });

  it("renders in Detail mode as well", () => {
    const html = render(model, "detail");
    expect(html).toContain("story-authorship-status--model");
  });

  it("renders NOTHING in Off mode (the not-seeing case is first-class)", () => {
    expect(render(model, "off")).toBe("");
  });

  it("renders nothing when there is no frontier turn", () => {
    expect(render(undefined, "ambient")).toBe("");
  });
});
